service: chat

package:
  individually: true

plugins:
  #  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs16.x

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
    environment:
      COOKIE_SECRET: LASJDLA3123LSDFSDF78SDFS5DFMHJ123CCC
      POSTGRE_DB_HOST: database-1.chwzotdkgmwi.eu-central-1.rds.amazonaws.com
      POSTGRE_DB_USER: postgres
      POSTGRE_DB_PASSWORD: 12345678
      POSTGRE_DB_DATABASE: chat
